---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: nexus
  name: nexus-data-pv
  labels:
    name: nexus-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 0.0.0.0
    path: /export/k8s/nexus/data
