---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: nexus
  name: nexus-data-pvc
spec:
  selector:
    matchLabels:
      name: nexus-data-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
